# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode API'
    veracodeAppProfile: 'ADO-Test-ENG'
    version: '$(build.buildNumber)'
    filepath: 'ver51856339.zip'
    sandboxName: 'Frontend-Test'
    createSandBox: true
    createProfile: true
    failBuildIfUploadAndScanBuildStepFails: true
    importResults: true
    failBuildOnPolicyFail: true
    maximumWaitTime: '30'
